workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: always

stages:
  - test
  - lint
  - build
  - publish

include:
  - component: $CI_SERVER_FQDN/patrick.pfenning.92/ci-templates/pre-commit@0.6.0
  - component: $CI_SERVER_FQDN/patrick.pfenning.92/ci-templates/security@0.6.0
  - component: $CI_SERVER_FQDN/patrick.pfenning.92/ci-templates/npm-publish@0.9.0
    inputs:
      scope: "@chromagoth"
      registry: gitlab
      registry_uri: $CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/npm/
      token: $CI_JOB_TOKEN

build:
  image:
    name: registry.gitlab.com/chromagoth/palettes:0.1.1
    entrypoint: [""]
  stage: build
  script:
    - chromagoth render
  artifacts:
    paths:
      - dist/
